import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dev Station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body
          className={`${inter.className} min-h-screen bg-gradient-to-r from-[#6C00A2] to-[#001152]`}
        >
          <NextTopLoader />
          <main className="min-h-screen">{children}</main>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
