import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { BackgroundGradientAnimation } from "@/components/aceternityui/background-gradient-animation";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dev Station",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={`${inter.className} min-h-screen`}>
          {/* <BackgroundGradientAnimation> */}
          {/* <Header /> */}
          <main className="min-h-screen">{children}</main>
          <Toaster />
          {/* </BackgroundGradientAnimation> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
